### ISSUE TITLE
Some company icons not showing correctly

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/companiesdb#344] opened 2024-01-16 04:59 UTC
Some company icons aren't showing correctly in AdGuard DNS, but show correctly when using the AdGuard icon service. Examples below

<img width="122" alt="Screenshot 2024-01-16 at 2 51 18 pm" src="https://github.com/AdguardTeam/companiesdb/assets/149243371/7e4b9211-7eac-49e4-a6b9-cfcad12254f8">
<img width="176" alt="Screenshot 2024-01-16 at 2 57 41 pm" src="https://github.com/AdguardTeam/companiesdb/assets/149243371/6628f90c-361a-464a-94f2-49756c957f26">

<img width="199" alt="Screenshot 2024-01-16 at 2 53 42 pm" src="https://github.com/AdguardTeam/companiesdb/assets/149243371/9ef75155-9c63-4450-a6fe-c48ac0aa4a4f">
<img width="190" alt="Screenshot 2024-01-16 at 2 58 30 pm" src="https://github.com/AdguardTeam/companiesdb/assets/149243371/b057eb13-83ef-46ab-8a4a-f5f39bd0ce0b">

**Comment by jellizaveta** [comment] 2024-07-05 09:44
Duplicate of https://github.com/AdguardTeam/companiesdb/issues/209

**Closed by jellizaveta** 2024-07-05 09:44 UTC
